### ISSUE TITLE
DaysOfWeek

### ISSUE THREAD

**Issue by timhowgego** [planarnetwork/transxchange2gtfs#10]
Within VehicleJourney > OperatingProfile > RegularDayType > DaysOfWeek, Transxchange2gtfs is only reading the first entry it encounters. Hence `<MondayToFriday />` is processed correctly as all 5 days, but the full sequence `<Monday /> <Tuesday /> <Wednesday /> <Thursday /> <Friday />` equates to only Monday.

**Comment by linusnorton** [comment]
Hi, thanks for raising this issue. Would you be able to attach an example file I can use for testing?

**Comment by timhowgego** [comment]
Simple example from the National Coach dataset - [National_Express_NX_atco_NATX_675.xml](https://github.com/planarnetwork/transxchange2gtfs/files/3053848/National_Express_NX_atco_NATX_675.zip) - 675 Minehead-Wolverhampton summertime. Journey JB5F32 Monday only, JB5F33 Monday and Friday, JC5F34 Friday only. Assigned trip 1, 2, 3 in GTFS. However GTFS is produced with only 2 calendars, Monday only (trip 1 and 2), and Friday only (trip 3). However trip 2 should also operate on Friday. Ergo the second day criteria is lost. This is a fairly widespread problem, which you will also find in much Traveline data.

**Comment by linusnorton** [comment]
Thanks, I will look into it shortly.

**Comment by linusnorton** [comment]
@timhowgego this has been fixed and released as 1.2.1 - thanks again for reporting the issue.
