### ISSUE TITLE
Stop times file: issue with hour field greater than 24 

### ISSUE THREAD

**Issue by lfigueira** [planarnetwork/transxchange2gtfs#15]
Hi, I've just ran your tool on the Traveline dataset EM data and I noticed that quite a few rows on the _stop_times.txt_ file have the hour as greater or equal to 24 (on both the arrival and departure times fields). For instance: 

> 83027,23:58:00,23:58:00,3390LE18,48,,0,0,,0
> 83027,23:59:00,23:59:00,3390LE19,49,,0,0,,0
> 83027,**24:00:00,24:00:00**,3390LE20,50,,0,0,,0
> 83027,**24:01:00,24:01:00**,3390LE21,51,,0,0,,0
> 83027,**24:02:00,24:02:00**,3390LE31,52,,0,0,,0
> 83027,**24:03:00,24:03:00**,3390LE43,53,,0,0,,0
> 83027,**24:04:00,24:04:00**,3390C9,54,,0,0,,0
> 83027,**24:05:00,24:05:00**,3390F1,55,,1,0,,1

Is this a known issue? Let me know if I can give any further details.

**Comment by linusnorton** [comment]
Nope, that's expected behaviour. GTFS allows +24hour times to represent services that start on one day and continue into the next. See the time field in this section:

https://developers.google.com/transit/gtfs/reference/#field-types

**Comment by lfigueira** [comment]
OK - my bad. Many thanks for the reference!
