### ISSUE TITLE
Undefined route type in routes.txt

### ISSUE THREAD

**Issue by tengl** [planarnetwork/transxchange2gtfs#16]
I tried to use the GB bus services feed from transitfeeds.com but was unable to parse it because `route_type` was `undefined` in _routes.txt_. Not sure if this is the place to report it, but I couldn't find any other way to contact you. 

See example from line 1806 (19 June 2019)
```
25-DLR-_-y05-10,OId_DLR,DLR,"Tower Gateway/Stratford/Stratford International - Beckton/Lewisham/Woolwich Arsenal",undefined,,,,"Tower Gateway/Stratford/Stratford International - Beckton/Lewisham/Woolwich Arsenal"
```

**Comment by linusnorton** [comment]
Hi, would you be able to link the file?

**Comment by tengl** [comment]
It is the one found here
http://transitfeeds.com/p/traveline/1033/latest

**Comment by linusnorton** [comment]
Sorry, I no longer maintain the full bus data set. You can re-make it yourself with gtfsmerge and the individual bus feeds
