### ISSUE TITLE
CSV files don't wrap entities with commas

### ISSUE THREAD

**Issue by markerpen** [planarnetwork/transxchange2gtfs#17]
Hi there,

On your hosted NCSD GTFS feed, the agency.txt file is malformed, specifically on line 6:

`OId_NXAP,Formerly National Express Jetlink, AirLink, Spee,http://agency.com,Europe/London,en,,`

What's happening here is that the agency name has commas as part of its name which our parser is reading as the next column. Possible to update your CSV writer to wrap entities that have commas within quotes?

This isn't just isolated to the NCSD agency.txt - it affects any CSV file where a name might have commas.

[agency.txt](https://github.com/planarnetwork/transxchange2gtfs/files/3646418/agency.txt)

**Comment by linusnorton** [comment]
@markerpen thanks for reporting this - it has been fixed as part of the 1.4.0 release. I've tested it locally with the NCSD dataset and it appears fine but it was a fairly superficial scan.

**Comment by chadselph** [comment]
I think it would be better to use a proper CSV implementation; the [`quote` method here](https://github.com/planarnetwork/transxchange2gtfs/commit/670948c009dce71c9e161d08934e47e854e3e156#diff-c668606eefdeea33cc99f749d48cdb08836bce6ff95551fa8e89ad95e7d27d41R42-R45) has a few bugs. In the GTFS spec:

> Field values that contain quotation marks or commas must be enclosed within quotation marks. In addition, each quotation mark in the field value must be preceded with a quotation mark. This is consistent with the manner in which Microsoft Excel outputs comma-delimited (CSV) files. For more information on the CSV file format, see http://tools.ietf.org/html/rfc4180. The following example demonstrates how a field value would appear in a comma-delimited file:
> 
> - **Original field value:** Contains "quotes", commas and text
> - **Field value in CSV file:** "Contains ""quotes"", commas and text"

**Comment by linusnorton** [comment]
Agreed. At the time I wrote this I was using it for some extremely large files and performance was paramount so I ended up not using a CSV library to reduce the time to put files though. I'd be happy to reconsider now as it using a CSV library would be more robust.

**Comment by chadselph** [comment]
I think technically the only thing quote is missing is the double "s; so adding that might be enough. I was surprised that `csv-stringify` doesn't have a stand-alone quote method.
