### ISSUE TITLE
trips.txt only shows one destination instead of two for some routes

### ISSUE THREAD

**Issue by markerpen** [planarnetwork/transxchange2gtfs#18]
Hi there,

I've noticed on some routes (LBAO022 for Edinburgh Buses service 22, for example) the inbound destination is the same as the outbound destination, even though it should be different (the outbound destination is 'Gyle Centre' in the TransXChange file, but is 'Ocean Terminal' in the GTFS file).

Any possibility of fixing this? You've done a great job so far in creating a reliable GTFS feed.

**Comment by linusnorton** [comment]
Hi @markerpen I can take a look - do you have a TransXchange file I can use to replicate the problem?

**Comment by markerpen** [comment]
hi @linusnorton - I've attached the relevant NaPTAN file - you'll see in the Services->Service->StandardService node (line 128232) the Origin ('Gyle Centre') isn't used for inbound journeys, instead the Destination (which should be used on outbound journeys) is used instead.
[SVRLBAO022.xml.zip](https://github.com/planarnetwork/transxchange2gtfs/files/3898256/SVRLBAO022.xml.zip)

**Comment by linusnorton** [comment]
@markerpen I've just pushed a fix and released version 1.4.1 which should fix this issue. 

I found that the trip headsign was not being reversed for inbound journeys but trip stop times were correct.

**Comment by markerpen** [comment]
Great job - thanks for all your hard work!
