### ISSUE TITLE
Agency URL

### ISSUE THREAD

**Issue by chadselph** [planarnetwork/transxchange2gtfs#29]
So I realize there's no source of an agency URL in transxchange, and it is required in GTFS, but I don't think hardcoding  `http://agency.com` is the best workaround.

I think leaving it blank would be better than using a fake website if you expect users will edit the final result before using it.

If your idea is the converter should return an immediately useful gtfs feed, then maybe it should take an `--agency-url` option as a command line argument?

**Comment by linusnorton** [comment]
It's a required field so I'm inclined to leave something in order to prevent validation options, but there should be an option to set it. I will see if I can knock something up later in the week

**Comment by chadselph** [comment]
Thanks! I wasn't sure what your vision was for this kind of thing; there's other places where per-run settings make sense. I could see it being CLI flags or a config file.

I also saw that the timezone is hardcoded. This is definitely a minor nit, maybe even just pedantic, but it could make sense to have that passed in too (if so, London should definitely be the default).

We're also trying to support multiple agencies with the same logic, and for that we will need things like trip_id, block_id to use specific naming conventions (so that they can be joined with the real-time data). So whatever mechanism for passing those options you come up with I can follow for those PRs.

**Comment by linusnorton** [comment]
Sorry for the delay, I've implemented this in a fairly crude manner for now. I've updated the readme but essentially you use env vars to set AGENCY_URL, AGENCY_LANG and AGENCY_TIMEZONE
