### ISSUE TITLE
NaPTAN ZIP file outdated

### ISSUE THREAD

**Issue by markerpen** [planarnetwork/transxchange2gtfs#3]
First of all - great project, well done!

This project uses a ZIP file of the NaPTAN CSV stop list, which is now 3 months old. Since NaPTAN changes regularly, with stops added and removed, and stops changing location (a bus shelter being moved 20m down a street, for example), it might be better if the project downloaded the latest copy of the NaPTAN CSV file directly which is available at the static URL 
http://naptan.app.dft.gov.uk/DataRequest/Naptan.ashx?format=csv

The project could keep the stored ZIP file as a fallback if the online CSV file isn't available.

**Comment by linusnorton** [comment]
Thanks, I hope it's been useful. I will issue a new version shortly.

**Comment by linusnorton** [comment]
Unfortunately the online CSV is too large to fit into a reasonable amount of memory so I have to manually edit it before adding it to the project. It would be nice to have a better solution. For now I've released 1.0.3 with an updated Stops.zip
