### ISSUE TITLE
Stops not found in Stops.zip return non-sensical lat/lng

### ISSUE THREAD

**Issue by chadselph** [planarnetwork/transxchange2gtfs#30]
If a stop isn't found, it gets a lon/lat of 0,0. Which is in fact a real location, in the middle of the ocean.

I'm not sure what the correct behavior would be in this case, but I'm sure this is not it. Even just throwing an error would be an improvement, curious how the maintainers feel about this.

Here's the specific code: https://github.com/planarnetwork/transxchange2gtfs/blob/master/src/transxchange/TransXChangeStream.ts#L60-L63

And live footage of the consequences:
![](https://media.giphy.com/media/3orieMtrBok8ZkW4h2/giphy.gif)

**Comment by linusnorton** [comment]
It's a required field: https://developers.google.com/transit/gtfs/reference#stopstxt so I'm not quite sure what the best thing to do is.

**Comment by linusnorton** [comment]
I'm open to suggestion but for now I'll close this. My reasoning is that some people run these files through some validation and I'd rather conform to the standard, even if it means providing some incorrect data where none is available.
