### ISSUE TITLE
Automate fetching of naptan

### ISSUE THREAD

**Issue by chadselph** [planarnetwork/transxchange2gtfs#34]
I've been finding it a bit difficult to remember how to update the Stops.zip file, and it seems to need to be updated almost every time there's a change.

I have a branch with this an npm script that automatically downloads and correctly formats Stops.zip: https://github.com/SwiftlyInc/transxchange2gtfs/blob/4264e4093ff753a9a1d1871b6c218f82cf8e3e99/src/get-latest-naptan.ts

I can't directly send a PR because there's other changes on that branch (such as failing the processor if the stop isn't in naptan), but if you're interested in it, I can make one. Also, feel free to just copy it yourself.

**Comment by linusnorton** [comment]
@chadselph I've just released version 1.8 which changes the way the stops data is handled. Now it will download it on first run and you can refresh it with --update-stops.
