### ISSUE TITLE
Error: Callback called multiple times

### ISSUE THREAD

**Issue by abdurashidv** [planarnetwork/transxchange2gtfs#35]
I have below error for certain files:
`
<pre>Processing sample.xml
events.js:292
      throw er; // Unhandled &apos;error&apos; event
      ^

Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
<font color="#555753">    at XMLStream.afterTransform (internal/streams/transform.js:94:31)</font>
    at XMLStream._transform (/usr/local/lib/node_modules/<u style="text-decoration-style:single">transxchange2gtfs</u>/dist/src/xml/XMLStream.js:22:13)
Emitted &apos;error&apos; event on XMLStream instance at:
<font color="#555753">    at emitErrorNT (internal/streams/destroy.js:106:8)</font>
<font color="#555753">    at emitErrorCloseNT (internal/streams/destroy.js:74:3)</font>
<font color="#555753">    at processTicksAndRejections (internal/process/task_queues.js:80:21)</font> {
  code: <font color="#4E9A06">&apos;ERR_MULTIPLE_CALLBACK&apos;</font>
}
</pre>
`
[sample.zip](https://github.com/planarnetwork/transxchange2gtfs/files/6066549/sample.zip)
Is there a way to fix it?

**Comment by linusnorton** [comment]
This has been fixed in https://github.com/planarnetwork/transxchange2gtfs/commit/52cb1b1b9d7578495518e13cb1454f48a4c68dce and released as version 1.8.1

**Comment by abdurashidv** [comment]
Thanks @linusnorton.
