### ISSUE TITLE
wrong agency merging by id/ref

### ISSUE THREAD

**Issue by tafflin** [planarnetwork/transxchange2gtfs#39]
While converting Traveline into GTFS I noticed that 2700 files contain same <Operator id="O1"> as well as <RegisteredOperatorRef>O1</RegisteredOperatorRef>. However all these 2700 files are routes operated by different agencies, they have different national operator codes / operator codes / operator names.
Since the operator id or ref are the same - "O1", they all merge into 1 agency which is wrong.

How can it be addressed? Maybe by combining the id/ref with additional fields from .xml so that the resulting agency_id in gtfs is unique? For example: agency_id=O1_BEVC (where BEVC=national operator code)

Some examples of XML transxchange data:
```
<Operator id="O1">
      <NationalOperatorCode>FCYM</NationalOperatorCode>
      <OperatorCode>FCYM</OperatorCode>
      <OperatorShortName>First Cymru</OperatorShortName>
    </Operator>
```

```
<Operator id="O1">
      <NationalOperatorCode>BEVC</NationalOperatorCode>
      <OperatorCode>BEVC</OperatorCode>
      <OperatorShortName>Belle Vue</OperatorShortName>
      <OperatorNameOnLicence>Belle Vue Manchester Ltd</OperatorNameOnLicence>
      <TradingName>Belle Vue Coaches</TradingName>
      <LicenceNumber>PC0004217</LicenceNumber>
      <LicenceClassification>standardNational</LicenceClassification>
    </Operator>
  </Operators>
```

**Comment by linusnorton** [comment]
A fix for this has been released in 1.8.3

**Comment by tafflin** [comment]
Hi @linusnorton,
Thanks for the quick response.
Unfortunately this fix doesn't work properly. In the routes table there is no link with the updated agency table. 
I can see that agency_ids were updated with the new logic but they are not present in routes.txt after conversion.

Also do you differentiate between OperatorCode and NationalOperatorCode? I believe it is preferrable to use NOC if exists (since it is the most up to date method of defining agencies). If not then OperatorCode. E.g. there can be problems when converting DFT transxchange files into GTFS.

**Comment by linusnorton** [comment]
@tafflin ooh crikey, sorry it's been a while and I did not think that through

**Comment by linusnorton** [comment]
I'm not sure it will be possible as a Service only has `RegisteredOperatorRef`

**Comment by tafflin** [comment]
Do you know any other way to separate the agencies?

Our another idea was to modify the .xml files before converting. But it's even more problematic. Will it work? what should be changed then?

**Comment by linusnorton** [comment]
I've reverted this change. I can't think of a way to link back from the service to the correct operator at the moment

**Comment by drfraser** [comment]
Hi, first, thanks for the software!

I am trying to solve this problem of converting Traveline XML files into GTFS and how to deal with merging the output of this utility for different regions (SE/SW/London...) into something comprehensive. transxchange2gtfs works great for a single region, but trying to merge the CSV files for two or more regions has problems.  

So this problem of agency id, etc is one thing...  Searching for more info, I found this

https://www.pti.org.uk/system/files/files/TransXChange%20UK%20PTI%20Profile%20v1.1.pdf

and it clearly states that TXC-PTI mandates operator ids are for internal use (e.g. the XML file itself), that only one operator shall be defined for an XML file and only one Service as well.  So, unless I have misunderstood something, or if TXC files for the UK are not guaranteed to follow TXC-PTI, linking the single Service to the single Operator should be straightforward.

I have only just started learning this stuff, so if there is something I am missing, please let me know. 

that said... I just found 2 XML files with 2 Operators. well, one Operator with two different IDs used in different spots.  I still think this id is an internal thing and ought not to be used across XML files.
