### ISSUE TITLE
First stop of each trip in stop_times.txt is timed 12 hours early where trip starts after 13:00

### ISSUE THREAD

**Issue by timhowgego** [planarnetwork/transxchange2gtfs#4]
First stop of each trip in stop_times.txt is timed 12 hours early where trip starts after 13:00. Issue exists in UK Traveline and National Coach datasets, so should be easily reproduced. For example with a recent coach dataset, the error becomes apparent from the 12th trip in the outputted stop_times.

**Comment by linusnorton** [comment]
Thanks for reporting this issue. It has been fixed and released as 1.0.6
