### ISSUE TITLE
Skip corrupt files

### ISSUE THREAD

**Issue by tafflin** [planarnetwork/transxchange2gtfs#48]
Hi @linusnorton ,
In the latest Traveline data we found that ~10 files in EM.zip are corrupt and do not contain all the necessary fields.
Is it possible to skip such files during the conversion? In the previous issues you already implemented a skip for those files without vehicle journeys, now the files do not have Services as well as VehicleJourney.
[TXC211219-211230-N89.zip](https://github.com/planarnetwork/transxchange2gtfs/files/7743364/TXC211219-211230-N89.zip)

**Comment by linusnorton** [comment]
Released in version 1.9,2
