### ISSUE TITLE
NAPTAN link changed

### ISSUE THREAD

**Issue by tafflin** [planarnetwork/transxchange2gtfs#49]
Hi @linusnorton ,

Looks like NAPTAN for some reason decided to change their website since 14.01.2022 and now they provide the stops.csv by another link: https://beta-naptan.dft.gov.uk/Download/File/Stops.csv

The download page is now: https://beta-naptan.dft.gov.uk/Download/National
The file is provided in csv and I cannot also find other additional files like stop areas, rail reference, etc that were available in NAPTAN zip.

**Comment by dannywithington** [comment]
On a related note, is it possible to prevent the NAPTAN from from downloading at first use? 

transxchange2gtfs is a superb piece of software, but as someone who mainly uses it offline, it doesn't function without first downloading the NAPTAN file.

Keep up the good work.
Danny.

**Comment by tafflin** [comment]
@dannywithington You can actually use it without downloading the latest NAPTAN. 
The converter looks for the latest converted naptan: /tmp/Stops.csv
We now have to temporarily use the older ver of naptan or process it and put in /tmp folder.

**Comment by linusnorton** [comment]
@dannywithington if you use it offline do you want the option to not use the stops data?

**Comment by linusnorton** [comment]
I've published version 1.10.0 which should contain the correct location for stop data. It also adds the ability to skip downloading stop data with the flag `skip-stops`

**Comment by tafflin** [comment]
@linusnorton what does this flag do? E.g. if I don't have Stops.csv in /tmp it throws an exception. If I have such file then it uses it in conversion. 
Previously if you had the naptan file and did not use --update-stops flag the utility similarly used the old one in /tmp folder.

**Comment by tafflin** [comment]
@linusnorton @dannywithington 
There is also a problem with the latest NAPTAN as it lacks lat/lon coordinates for ~200k stops (they only have easting/northing). I'm in contact with naptan team, hope they will fix it soon. 
Currently a good option would have been to auto convert the missing coordinates from projection to lat/lon.

I've also a suggestion about the new stops.txt format after conversion, previously the stops not found in naptan had 0,0 as lat,lon. It was more convenient than empty value.

**Comment by linusnorton** [comment]
Sorry there was an issue with `--skip-stops`. If you add that command it will not download naptan data and just use the information from the transxchange file for the stops

**Comment by tafflin** [comment]
@linusnorton @dannywithington 
There is also a problem with the latest NAPTAN as it lacks lat/lon coordinates for ~200k stops (they only have easting/northing). I'm in contact with naptan team, hope they will fix it soon. 
Currently a good option would have been to auto convert the missing coordinates from projection to lat/lon.

I've also a suggestion about the new stops.txt format after conversion, previously the stops not found in naptan had 0,0 as lat,lon. It was more convenient than empty value.
