### ISSUE TITLE
cli tool failing to create stops.csv Error: ENOENT:

### ISSUE THREAD

**Issue by alexdawn** [planarnetwork/transxchange2gtfs#5]
```
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\tmp\transxchange2gtfs_stops\Stops.csv'
```
I will try creating the path to see if its just a permissions issue, but ideally the program should not require some particular path to be valid

UPDATE: yes by creating an empty text file of the same name works around the issue

**Comment by linusnorton** [comment]
I'm sorry but Windows is not supported at this time
