### ISSUE TITLE
route_short_name not populated

### ISSUE THREAD

**Issue by thomparker** [planarnetwork/transxchange2gtfs#7]
This is great. Only issue discovered so far is that in routes.txt the route_short_name is a duplication of route_id, but it should be the friendly name of the route.

**Comment by linusnorton** [comment]
I'm open to changing this but I'd need to know which field to use in the transxchange document. At the moment the long description comes from the service description (http://naptan.dft.gov.uk/transxchange/schema/2.5/doc/TransXChangeSchemaGuide-2.5-v-57.pdf#%5B%7B%22num%22%3A149%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C87%2C304%2C0%5D) do you have a suggestion?

**Comment by linusnorton** [comment]
That's an array, should I just take the first element?

**Comment by thomparker** [comment]
I think so. Does that mean in theory a route could have more than one name? As far as I can see in all the Travel Line data there is only one LineName per file. Thanks!

**Comment by linusnorton** [comment]
This has been released as version 1.0.7
